server:
  port: 8081
spring:
  profiles:
    active: chaos-monkey

management:
  endpoint:
    chaosmonkey:
      enabled: true
  endpoints:
    web:
      exposure:
        include: chaosmonkey

chaos:
  monkey:
    enabled: true
    watcher:
      controller: true # Enable Chaos Monkey for Spring controllers
      restController: true # Specifically target REST controllers
      service: false # Disable for services, can be set to true if needed
      repository: false # Disable for repositories, can be set to true if needed
    assaults:
      level: 5 # This is the default level of chaos. Higher values mean more chaos.
      latencyRangeStart: 1000 # Minimum latency in milliseconds
      latencyRangeEnd: 9999 # Maximum latency in milliseconds
      latencyActive: true # Enable latency assaults
      exceptionsActive: true # Enable exception assaults
